#pragma once

#define MASTER_LEFT
#define SPLIT_USB_DETECT

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 170 // was 200
#define TAPPING_TOGGLE 1

#define COMBO_COUNT 1

#ifdef RGBLIGHT_ENABLE
    #define SPLIT_TRANSPORT_MIRROR
    /* #define RGBLIGHT_SPLIT */
    /* #define SPLIT_LAYER_STATE_ENABLE */
    /* #define RGBLIGHT_EFFECT_BREATHING */
    #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    /* #define RGBLIGHT_EFFECT_RAINBOW_SWIRL */
    /* #define RGBLIGHT_EFFECT_KNIGHT */
    /* #define RGBLIGHT_EFFECT_CHRISTMAS */
    /* #define RGBLIGHT_EFFECT_STATIC_GRADIENT */
    /* #define RGBLIGHT_EFFECT_RGB_TEST */
    /* #define RGBLIGHT_EFFECT_ALTERNATING */
    #define RGBLIGHT_EFFECT_TWINKLE
    #define RGBLIGHT_LIMIT_VAL 220
    #define RGBLIGHT_HUE_STEP 10
    #define RGBLIGHT_SAT_STEP 17
    #define RGBLIGHT_VAL_STEP 20
#endif
#ifdef RGB_MATRIX_ENABLE
    #define RGB_MATRIX_KEYPRESSES
    #define RGB_MATRIX_FRAMEBUFFER_EFFECTS
    #define ENABLE_RGB_MATRIX_SPLASH
#endif

#ifdef OLED_ENABLE
    #define OLED_FONT_H "keyboards/crkbd/lib/glcdfont.c"
#endif
